package main

import (
	"fmt"
	"strings"
)

var input = "BzRmmzZHzVBzgVQmZLPtqqffPqWqJmPLlL\nhpvvTDcrCjhpcrvcGGhfLHMlLtMCqflNlWPJlJ\nhGjhncHhGnhbTHczBBZVVSbRwgSgRV\nrWVQjPQQjGRWNSrWrPjcptwBpqqJBtJBBcZgMdtq\nzzmmpzfTCFpTlMlJJwBgMlqMBt\nTvLszpbhhTLmsnRQPDQGWDWRvQSR\nzGzvLlGlQHLGBQZlhBWhdjRdmdWRcjPj\nfTJNfTfNSRWPhjdjfj\npbsbVVnpSnbVTprnbqqrzvLLgQlGLPLHll\nZCCCsWvNvmsCsCmZLZmgMLRpQMhwQRpQRfphfprpTfpM\ntlncPjzlndctbzcPPBcjwDphwrfGGDffbDRpDTGG\ncdqnddwzqjNVWVLZZLZq\nDTLbDbRrlQbwhhNrmmfwdt\nzzMJMzjCjJJjvLjMPJpcgPpzfhHdfqWcqddwtwfqdttcNtdN\npJCzVpCvDZBLsVRQ\nSTzBBbJzRRBZBRTqCCsfZLtNNLClCsfh\njsQnnQjjHcvQFrcPwCmtLCNlvDfftfff\nsGFscMQQMMpqzqbMbd\nQlNDWGsjQjgQllWQsbtzqTJczTJcbFmmFJJP\nMhLrhgLVndRmzJFzVqqJqP\npSLnMdwhwdRZRSwhLZwLhdGWQjlsgWjNQWWSvgBsWDlj\nTHjSRFSddTjdBTcPLcVVvVBw\nGzWnWfndWfznDfsnsBsPVwVwPPLL\nzNflzJWqqzQDdSStHNZNpFFtbj\nFSzDmsFSFlDlBzqVjqHHjHHpVgHLbp\nrTrTtTQQntRQnQJQgggHZttVgHLBLhZL\nWTJJRRQCRRJTRdBCRdvRNDFSWFMPmDlPPSsNPSzS\nWQldlMtMVQgVMQHnDGbHGGnRnQmD\nrqcZPrCFjmHlbGjZ\nzSScchqwchBzTzFzhhSlcCwNtdVWWJgsVdMtWNgNVWTJTd\nlMZqjMWllrTTspjprWWSSwgWNSVNDmWGVwFwgN\ncdCCdLHcnndHJnmCRntLBnRzDvFNtNDVzgSgwDgFNVzFVv\nBRLcCCJCmJdcRhfjPPZphrlrPqlZ\nGdGqcrrZGDrvDJJqJHcBvmFFgmFMMgMgBtMLTssLmF\nNbPVPDlljPmTmsTj\nVfQDhflCCRWdcrQwJvvnJv\nRLcWgLCqqPQLcqZwzHgwmmrmmtgwTw\nDhbhNrMpnJSDJwVTHmmTVnTTVj\nlrsvblMDlcWcfQPQ\nPVldlphHwGwJJGdjZZWsRbbsGsNWrWQbNbQR\nSqcDvTmDLtfmSmtqppfqzTgTQBrRQsbCFWbNNFQFBBrRbLNb\nMgtmTgtfpqVlnVddZMwV\nBdmfmPBPSbSNdGSdvWrwcZrccZPPcZnH\njzzLsjsMRlQQVHwswvvZrCHrrT\nVqhzVFzplFlpLwpMphLRQQVRmSqgbdGtNJBmNSmgGbtggSgt\nDHVpNZjdZjFZWVFHpvFvzmlRzPnlfznFRz\nlrTBTsBwwMbrrwLPPfwGmGzvRf\nscrtMhMCtJBBBclbHdHttWZWDSqDSjHj\nwzqsPmqsbsfqBwPMNRMMZcZmFFNtZM\nCgCnhlvvLJgcRFNNBdCpWM\nQnQrVgHSvVHjbjTGBbbTHb\nHdrVrdqFDdZVmHgRmDRFHMnTdTssMGnLnPJLbPTbCs\nSczlScjwcNzplNzQSSfjwQSrTGGsbTsnTCnGTMCMLMGGbN\nwQlfjrhfhQFHqZhRZRtD\nRsfJDGJvzPNcjpddSWJWMd\nLLCbBCwCrCmVVnrmhQFmbVhdcdlWpjZzSpMdWSpcWczSBj\nrrLCbTwnHTvzvNGT\nwPhPhbCqqSCrtJDlqvlrJr\nRVVZddLFRZZcQLvJJtzptlgPJp\nTVQRZGVncFdTGWZdCNShHhfPNwwsWPwb\ndzLVzPSgrgDDDCMSMLLPwFmdTTcsvmwNwjNsHcFF\nnWBGntQfGNGBflWBBqlpRQGbWFvjwsbsFswbvTHjjbmHTc\ntBNJBnGBflQnDPJrPhDgrPVg\nVtWztWtqpqzWpWzqjNRjNpWTmrrmrSbnmJwSJwnMPrCSJVwM\nsDHsBDhBdsBZGcHvLHDLhhCSnRSwCJMZrPbmnMbJSCSR\nccLRhgsLBdRsdHNTFFNNgqTglqzF\nhztlmDhPhgPlPNNgmZMCbmwwQjcwjjwMjVCd\nRSJRrRqnqQJFqvnTGrHCcHHCCHHbHHMcMvdM\nqGJsnQTRsStsftPlhPNl\nBFFBLPRCwsLwhlPlRmhcGGrbmmGjfNTTnp\nVJMVpzgqggJnrjmjNcMjmT\nVqdSZtQgZvtdzqHqHtVZdVQpCDWWFdwlRPDpWPPBCswlWD\nfCWCsjPzcbzwRSzVTzhhDLqvdg\nTmJtrNJrBLSLJqgS\nptNTQFHrZlnpFPwsWMbRjCpcjR\nnJmQNCmbmlllmbClbfMLjMFqbGBsdLFq\nZcgTWcTnMqqMTBqF\ntPgctSnPctZZgDWzZgQHwNmHlhlmzlQhlJlw\nZpTCwpffdslvgShCBhqhRz\nFDMPnNFNmBPzvRPRBg\nnNgMrnnDGjDmJMmnFdZTTsdsrZrslcwcQr\npTmczpCldcdDDnPttpvWSqbpJf\njgjRZMGHhGLgQrjvPWzPJgJvzStbbq\nLGNLLNBBzcDFCBwwFC\nnJTTqnrNvTzNMzzNfqrTPrJnwpwPpZpsHccZVsBRpcVHwpcp\nbgDhgbghLWmFmStctVpZtBCVCCpfZp\nLLSgLGSjggFGbSSbmMnrvqvzjfzTNrJrqM\nRRpDmmPMTjwfGmJQgQ\nWsNscdnvvdVZFVnnrZbjjflwljlbzfGFjQjq\nNnLZsNnrrVVVcvdBLTPCPCRMwhPMBMPhCt\nlbVvzngGJnVbJHpHtHNPpdSQvc\nTsMBswFZsWMWBZMNwPtNNtRNHcNpSQ\nCcZCTrZDsjZTsTsshWhrWrTnfgbLDfJzVVLVVlgfnzfVGV\nJzTTRtJRZWmWjrMHCT\nDDFGlLGcGlSSSLsFGBspPBmNMBHMghmWNmWjWCmWtH\nnSSpnbsGlLDnpPsSSspFtVvffRQdVzqvvbqdfVQwRz\nsMhzszlHHDsWbthHDqsbJjpLNtmjVJmVLLVLVLBp\nnrTPrGwfPLdprzJzdL\nwgPQcTGGzgccwCgnRwgRChFhlWSDqWWQMWhssSsMQl\nNSNmwtpSpCpvMphCsr\nPHcRGPLJMrsvzsqG\nQHjbnRMcfbPbQZmlZgZlgBBQ\ncPRPbhQjbQRdtPQdLqLHqzFZjCFCqLjC\nmmfsnnwrfvwrfSNZFzHHLDCFNlLlqDlN\nwsmrwswwGTffMrBnmQttJtcMZQQtPJPbZc\nMvBPDDRRdnnvHPCHZLHZsFLL\nrmJcbVqbcjWwWjQHLzTZFTHSzFrpsz\ncmwllVqqGJbVVVmmqbQcmgRnRvGhGfgDRDZBBBvRdd\nnMvMhMnvhnbTZWSSZgHmGJDFmmNDzBmbNmdGBN\nrCsPLRCssRjrLLsrLlwRVrcNJQfDQfdBmmfNBGJNzmDPfB\nCRjCpLltgtJgJJWq\njshCzJpjzTPpmCWvSlpfwHfSWglf\nLQMMNMnHtDtLVRvwwgRWlldgWD\nqHVrQNHVMFQtrrBBQMBcrrZsZbzCZhbbJZJsmmsmFPTC\nJZQZnsQNMqTngZqJBVfBfPPVBNrwvfPw\nSSmDstFjpDpCszDjcLLhrPVlGlrGGVBwrvwVPt\nFSssFcLjFjbmFFCzjLcFLRDnMJnTHRnZZTdWqZZWnMnRnZ\nGbHRHpldwGMpWhHpCMBlCbRdVSLhnqJLSrDPLPPLPDqVDrhh\ngvjWWQvgZFtQFFNqLnVnDnSJzzztDD\nZccccfTsffHdWWdRWwsw\nClCtbHMlnnPPlszV\ngSDWSLgWQWQJJNWqgtQjPsnfcdVcLVdVdzfzVzff\nWQgqtFQgDgQSFqJhqhSJvNDRrZMZHwHMCbZhTpZbGHMTMG\npZJZlCQtHFhPfdNfCh\nzcmLSVczwcMcLDNFHdLPhPWH\nszvVVnBmnTGQtHTQ\nRVVCNDlNGzlGZqHGHWqWhGqQwH\nZFLFTmpLvvmSqsbb\nTrfpBfJpJMlnnNfNZD\nqHHlDClHhltMqQsHDhHslGznwdTnzzwDGSdfnwGnwG\nmZRNcNcLLPNPBFFbbPmLmbZFSCVfJJTVndVfSwnRzznfTwCS\nCcCWFbbBLCWtgWgHjghqvv\nTjbzlnlFmfqCFFVVCRWr\nPhMcLpPDtMLpwPDvLPJbMhSgVCGqggVqQgCqCgCgSWvv\nbtbZbNZhJDJJhDtwtsTTTmBzzBBmlNlmHj\nFqhjWtqlqmmsnFPTCvMCQMTTCjQd\npfffRfLpgrgGgzrNVzzpGVzRCdMCPJbwwcVMbQPCJVMVdbww\nDGGDZRGrHggzSsFQnnWShmtH\nvtHVVMMrvVMVrSHvLgvlHcZFCnRCZcccZtRRZfJFCJ\nrdDjGsdTQDcNZfdncCRR\nrBDsTwBbjbmbbQswswPhqVmmSvpVhlvvqMhHhh\nvGBLrqMNvqSLBvvrNbllLHfwStWWtFttccjtRtjtcj\nMhCDJmhMDzmcRRcjzWfztH\nZQDmDhVVCQbBVdVNMvvv\nptCtCzhWPWptnhVzzpGZbZTjTjVjFGjVFgVl\nfQswRRffmRqZlgrqqFjjSgGg\nHwsQDNNsDsmRLLHmffsfvHptBnhtzCvhWpZWBdhnMdCh\nRlHzzTqczBPfbnvcpB\nwVtNwpSZstppwwMsZhsdnLvnbtBBmbnLFFdnmF\nWNQJMVWsZWwGJWhhSNrQzlgHrDCgQRHpCHrl\nRrZWpJZRrZpdTGstlchLGGlLMd\nNqjDPCQPnQCSvtMzSLhhjM\nnQVQDDDDfwBwNCVCNVFNpWpgJgrRTmLTmTmgRTWF\nSHMcrMHpcjGcjSrMMbvSvvSvwFTLJwJNtFGFWJNtDLFTLfWN\nzqRnPfzQCRzqsmRPzznhszzLtLwQwwFTgWWLDLgWFTwTNQ\nqVPZmRZhsCZPhZlRCqRRRCbfpccMBjvMVjdHjjMjSvdf\nVVQdHwBZLVltlddtBczhrzvGcWWFRwgsFG\nTDTTTqqTSSqjqnmTmPqPPmTmGhRszvsrzsjRsccgzrRzgWGF\nDpJPqpWqHbZpllpt\ncCSCFsnnZFnscDtNdJFJtJtdmb\nVgBqBsqRrHtNdzmNrt\nBGLLVVjRBsqPBfsGwPsMfSSZCSfTZTZQpSphfS\nplCHCHlgglHHGpNbtngNrDvBDpfQDBQfZDfWZVrr\nmTmMLhRfwhsLPQvQZDMZQBQWMB\ncwsssmqRTFFfFgtbCtGl\nLQPPrCPnMZwqtRMn\ncWTSlJWlcplJdDTdGdpDlGcGgqmtwwZtqRrNRRmRdNZqmgNq\nGSJcJSjsjTpsvWGWBHLLvVVBBBrFrzVz\nNVPCSPMNDSNFVSWCsJJJmpGmZZGLLcpZLHGGtsHt\nfwzlBBqghqvzqqlDrHbpHjZHmGZbLZrHLb\ndnBgnDqQvwRnSnnFMFMP\nBCbPsFFwCRHmDSBmWnvDDj\nphhZVzdpVfQZphhZpRhSVnjmrcvvnrWtDrvWDS\nTfQJMfLphMhJdfdzpQJRTPbwHHNlgbGwsTGgCP\nttWLlnnvnNnBBtlTqWlpvpndQdZsQQFssFDdsRFdVdRNFQ\njSgrScrbGZSGrrCGsFVMssFsPPFcDDMV\nbzSmJbfCZCbzLwllflwqtvvw\nzmFTJwFLPmzLztmjDzTJwfNrdFNrFppBSNRGNGdbrpBR\ngqlhWQgsZMsvqMlMMvsvqsNlLbcdppbrRpdbbcSrrbbr\nvssCgVgCsggZQZCgsnsqWgWvfJPDLwffwTPPmzTnjTPmPmwJ\nSpcRTPQLBLWpNNzjmmwwwRrR\ntGlfvGhfnbDlbqlChnfFMrwsmwNssTMHMHjFwv\nZlhtCtffCdWcZWZVVT\njTTCcWHWJNgCGTzTmnzrmnGn\nBwRRbFvtvvQmJJFMpMJr\nZBBwLvqbBZsRsbVsZSqbcZdJjHHjhfPCJfJfHhgc\nVrnDSvvrLrfTdTLGfdRp\nzcJzmcFcHGfdGmWTVd\ntHsMhwPVctccHFHFcbSDbbPjnNbBnbvBQB\nQttWQwLTnLnWTtnffnLQSBFVjNvBjBFNgMdCsVWsjv\npDqcmmRPHqgVBddjvN\nDcclzbcbPbJLnNTfnw\nplRcpsZDGlGZvWvMCNcLtttq\nSrfrwSjSVrSjwbmSrHzmHJCQQPQzqttNNQJMzJtqMW\nwSHVnfHfWwwHWFVfSnfgmmRsslFZZDBBGZsZsDTdGRTp\nqSFQSgQNgQBrBHHcrW\nVTmjVJLTwlTmwTVmsMJMVlJmPvcbvvbCBbGBPjGvBbBGWcbb\nDnJTZwmnZRhnpqNdWt\ndTVHjZLLZDVCfVHtLDDjQbscjWbSJMJPjsbWWb\nFnqrnmzzFllmsWwtsFtQMMFc\nlmqzzzngGmlNNBqGllzlBNRvptHHpTCHpDLpgDZdgvHvDD\nsdRZQbCfZTSTdlfTZCffccWPHPPcPPwLwctRnLWn\nBBJDzFVgCDrCJrqDJJhqJVVMLPHwcctFwcWHHGLcwGwGHnWc\nghpJgqqjCZbQdZpd\ntbcpzbHSszcHBgqHGZgJJJhhww\njfvdvRTffQQrrFCRFTnGwJRqNRZVpJGZLZggLh\nnQTjTnMndlTdQFMvnrClCnpzmzDtbbmBbcPSzzlmmtzP\nBqBqTCSTcqHsJHHM\nWWPGVPLtzVgWtjWPGzVjzVGcbDhPsRbDcsbJwNRswRDRss\nVQfWjfLFGWLjdFfVzTZZpJTpnmlTrSQlBl\njLNsZjqSHCsGdsmpsm\nMvnVFzWMwMVWzfnVDwfBMfnnrCtdtPmPlRrdrJCJrtPDrrPD\nzznfFWwMfMfFMwVTMQFnQjhjgjSZhCNbLSTcHHgbbC\nGGtssttVmvnnGNMQrrVzgwVrCWMz\nFdhfhhcCDhHLfzclZMcrwcQMZM\nHHqqCBhHSSpdmjGqmGjtjtjj\nbbQLtGMQQtQRQtrDtGprrrbCqwplZhhqSqmdwvdzqqqhSmpS\nFsJjJBfnsJcFcFfjVPjWBzldqhqnlZZZzzhmnSvSnm\nJPcFfFWjFHJVVsVjPVscsDlLNRHGDbLRMRCDNrCGbG\nJdMdlMRJnTwdvcjv\nCDLHbNSzzLFgHvnTjrswBNBTNT\nQgbvzSFQmZQPQQRW\nNTBrNzrpjjjCwGbB\nFRbQlcvFvcRQQlRsMlRRRZjwCqMwjmjwJZdLJmjCZC\ncVPPQcvlWDNhrbPz\nVdbVtbbZJdtJVVdDVZmTLqqTSQvNLjjDShhvSG\nzplpnBnFpnrrlghGNpLNqHvqvjNj\ncWncllnlPFWzcMwtWWtsVLVRmJWCds\nShLSTnZnTSttTSbLQdfSZTMwcDHwwcHnJvDHnlnlclMM\nNmPMsssRrVwjDclHJwwR\ngNNMWGzNmqGdtfZTbGGb\nsWNNlRHnmJtmntJt\nbrbbBTbbFbCbqqGgBTrCfmQVVZfSSQQSVtJZSrVZ\nbbFqvbDvvGGLGbCCtBGDLbLlcPNHhhccPNcdPPchlsdR\nDCFvDvnCnNfMBmMMslDZML\nSQQQJHwpSgJSJHQWSWHqJWWbmcBBBLLTsmhhTcZbMhmlshcb\nRJRgpJHssgwSQHRqsQPGGjjtNCrrFvvnFjjPrP\nmThmsgjzTPjMpcvtWP\nGNNBVqVGNZbbNbNqqZQVNVNbWcpdtMCcpCtMWCdCPpQccmpp\nVSmNrmmbBfZVlsrssrLTRhRhTn\nTdmCvLDCpTRNTdFbbWnnSWCfhjbbzn\nGrrMsPVGcQHBGMbhjjSgWfHHDbjb\nBPBVqqrQPsQqwrrmmmJdRLDDqFRplT\nfpDDJljDlCfDTjprjrfbddWthCSCtdPPQFhSSSWW\nHsLZgMGbgBBsNzMvGbdVtVQzFRQSthhFPdtP\nsMBmGBmbNvLHGMnrDppTcJmcjpqljf\nptSpSJQqpbNGGDDhcMWrlNHcZZWWls\nzRLRRRjvvgjHMMsMpWpc\nvmCPLCgwvwdnCzmvLbpTbVQqJJPbJPpTVq\nTJCfhhJVFffrJJQQllNWcvWhwvWD\nGPSGjjpLslBbpLpLqqqPDvdwvwvNzQWGzDDNdzGN\nmsbRjbpPqsRpHnlZrmJlnVHT\nGGfFsCCTvGDsfTTrhsCMMzptZJMdpdgtrpdMcV\nLBlwBHPSqjwwlVggHpnMZcVHMt\nZlZZlBbRPGGTGfmRsD\nCtCjbVvzQQZTWVdd\nMlSqWlmsmGBSHJHTDFHZ\npcqsmsplwsqclwRtRWgtRnPPvb\nzCrzCrsdjrhGDCFqGDjRRPtpWfQQcpfQZcCZPp\nVSVwVMgLHHLTwMDTMMVnbWPRZQRcRQPptWnpbZcb\nMNBBBlSMvLVwTlVTFdNdhNhFsqsGDrzm\nrBLWTwTThWwVVDTwHBsZZWppvpGtpptppmRvFFFMFMfL\nqPPNCCbqcbcNqbqQjjJQqzjRpptmlpMGmMlJtftmtFHpMt\nQnCgzzQbbQqPcPQnncbdQdnVTwDssZgrShBTVgZZsBSDHT\nPFGJFqnfqmPgFJQPWdbLdpDRhbphWjDm\nrclNHvcrzCNwrWRprjdMMMph\nwsZHwZNvRRQsQqBV\nLqlGCPlPLTCPqqQlpqLlWfBfWgcHNRJRfWNsncGH\nVVtdwVtDDdVmhrdwSBmjbdzNHgfgJnNnsSnHsNffHgRsgR\nwVzhbjmDbDrwjdbztFDDthMCvqPppZQBQLZQTqTvFTvZ\nBnQnQFwRmRwmwdBSFDFnmSDVLCJTCTppVVmGLVTCLcgVpC\nZlWvhvZjNrbNvqjNhlfPfqjCGHrsspggTpVLpsJCpcJVgg\nvPzNvqjWhqFzGSnRGMDG\nwZnMZzzZZchDRtVsqtCtwV\nWmWpWWmPPWrmrmBmWrTlTFPNVqVCRSDCQHcqVTtTqsSDSTSD\nPrppdFlWWlfrWmpWFffrdcGjJJGggnnhZGdLLgGGndvz\nFShHNmNhRhNJmBnQBQJrmP\nVTgzDTjwfffwzDvwlcczzVSJbQlBQSWBWCnPJPbJWWbC\ntzSVtzvSvGSRZqqFMNtpRR\nhPZhGDZpnCGtDhznjmLmdJffdNzJ\nglwsSrQwBvLdgLzdcj\nQsRbHllzzlHwHlBszWlTBFbpDPMhbPDVGpGFpPtFPp\nSRjStRDctgDSBzLvPvNrDhmPLr\nQqTHGTPJmmHmhNmH\nTGQZsTqFnQZCJTPsnJnZQMjVRBVtcVRSVRBlwccSCtBS\nbbsNsvsvnNPTRRllbblLqhtQCqQSLCGGHSqHNC\nwFpzFgqVzqVJWFDwqJDmSBBmHBHhShLQhCGSBCGH\nMJVpFMqgwMqRRbZsMbZMrP\nPPdDhvNDQdmgQPZmQVHHtHGGWVGbffWGvs\nMMLCTRRLlLclTLRMRLCwMLHWVctbVVHWWWFfVjVGsFWW\nMRSMMlpTJRqClBCRqBDnzqgQPnqgznZPZqbP\nMrMNPNNpjvdprWtrpMsthqBfqlnfqcGhVBqFRcnqFG\nQbDgSSQbgSDDmDVmlqSCRllRcFqnqfBl\nQVJbVmwwDQbzVTgbppNJNMWNjNNPrdpM\nWwJJNbtHfpLpVgZZPVFhZh\nvmmqlDvRvRfqBSrlzmmMjRBhcVhQVZhVghCQQQQTcTrPTP\njSqMmqRzMDDjvqlBqsBMBmmwGNJwJnwLNfbGwddswnJtJH\nRLgRmRggbvbzzPmmRNmzsQWFtSGNtwSNQnntFwnnCw\npDBrBHpHhlldphHBHhJVFSLnWWFJttCtQSttSS\nhfHrpphHBppfTvmzgMmbLbgf"

//BzRmmzZHzVBzgVQm
//LPtqqffPqWqJmPLlL
// BzRmmzZHzVBzgVQm
// ZLPtqqffPqWqJmPLlL

func main() {
	_ = level1
	level2()
}

func getPriority(c int32) int {
	if c > 96 {
		return int(c - 96)
	}

	return int(c - 38)
}

func level1() {
	chunks := strings.Split(input, "\n")

	sum := 0

	for _, line := range chunks {
		found := make(map[string]bool)
		center := len(line) / 2

		left := line[0:center]
		right := line[center:]

		for _, char := range left {
			found[string(char)] = true
		}

		for _, char := range right {
			if _, ok := found[string(char)]; ok {
				sum = sum + getPriority(char)

				break
			}
		}
	}

	fmt.Println(sum)
}

func level2() {
	chunks := strings.Split(input, "\n")

	sum := 0
	cur := 0

	group1 := make(map[string]bool)
	group2 := make(map[string]bool)

	for _, line := range chunks {
		cur = cur + 1

		if cur%3 == 1 {
			for _, char := range line {
				group1[string(char)] = true
			}

			continue
		}

		if cur%3 == 2 {
			for _, char := range line {
				if _, ok := group1[string(char)]; ok {
					group2[string(char)] = true
				}
			}

			continue
		}

		for _, char := range line {
			if _, ok := group2[string(char)]; ok {
				sum = sum + getPriority(char)

				break
			}

		}

		cur = 0
		group1 = make(map[string]bool)
		group2 = make(map[string]bool)
	}

	fmt.Println(sum)
}
